@startuml
skinparam maxMessageSize 200

participant "RIS" as R
participant "Modality" as M
participant "PACS" as P
participant "ISAI" as I
participant "3rd party\nalgorithms" as S

activate R
 -> R: 1. patient registration
activate I
group Patient flow optimization
R -> I: 2. patient registration（VDO)
R <- I: 3. propose worklist
activate M
deactivate I
R -> M: 5. send worklist
deactivate R
end

M -> M: 6. image acquisition
activate P
M -> P: 7. send DICOM images
deactivate M
activate R
P -> R: 8. notify image acquisition completed
deactivate R
group AI orchestration
activate I
P -> I: 9. notify image acquisition completed(VDO)
deactivate P

I -> I: 10. Filtering for notification based on supported modality type and body part
note over S
algorithms from
AI vendors
end note
I --> S: start AI instance
activate S
P <- I: 11. DICOM Q/R images
P -> I:
I -> S: 12. AI application execution
I <- S:
I --> S: tear down AI instance
end
deactivate S
deactivate I

group Interactive verification
activate R
I -> R: 13. update AI execution progress
I -> R: <font color="darkgreen">15. send AI result
note over R
User verify the result
by choosing accept/reject
on AI result dashboard
end note
R -> I: 17. Send the confirmed result
deactivate R
activate I
I -> S: 18. Send the confirmed results to algorithms(key image/json)
I -> P: 19. Store the AI-processed result images
end
@enduml

'/*
'优先级和参与者有关。
'Actors:
'----------
'Report Creator ?
'Report Reader ?
'Rendered Report Reader ?
'Report Repository ?
'Image Manager/Image Archive
'Image Display
'Image Display Invoker
'Evidence Creator
'Evidence Moderator ? <- ISAI
'*/