@startuml
'https://plantuml.com/object-diagram

scale 500 width

object DiagnosticReport {
    identifier : Identifier
    basedOn : Reference
    status : code [1..1]
    category : CodeableConcept
    <b><color brown>code : CodeableConcept [1..1]</color></b> <color #eee>X1</color>
    subject : Reference [0..1]
    encounter : Reference [0..1]
    effective[x] : DataType [0..1]
    issued : instant [0..1]
    performer : Reference
    resultsInterpreter : Reference
    specimen : Reference
    <b><color brown>result : Reference</color></b>
    note : Annotation
    imagingStudy : Reference
    composition : Reference [0..1]
    conclusion : string [0..1]
    conclusionCode : CodeableConcept
    presentedForm : Attachment
    Media
    comment : string [0..1]
    link : Reference [1..1]
}

object Observation{
    identifier : Identifier
    instantiates[x] : DataType [0..1]
    basedOn : Reference
    partOf : Reference
    status : code [1..1]
    category : CodeableConcept
    <b><color brown>code : CodeableConcept [1..1]</color></b> <color #eee>X1</color>
    subject : Reference [0..1]
    focus : Reference
    encounter : Reference [0..1]
    effective[x] : DataType [0..1]
    issued : instant [0..1]
    performer : Reference
    <b><color brown>value[x] : DataType [0..1]</color></b>
    dataAbsentReason : CodeableConcept [0..1]
    interpretation : CodeableConcept
    note : Annotation
    <b><color brown>bodySite : CodeableConcept [0..1]</color></b>
    method : CodeableConcept [0..1]
    specimen : Reference [0..1]
    device : Reference [0..1]
    hasMember : Reference
    derivedFrom : Reference
    ReferenceRange
    low : Quantity(SimpleQuantity) [0..1]
    high : Quantity(SimpleQuantity) [0..1]
    type : CodeableConcept [0..1]
    appliesTo : CodeableConcept
    age : Range [0..1]
    text : string [0..1]
}

package {
    object BodySite {

    }

    object Component {
        code : CodeableConcept [1..1]
        value[x] : DataType [0..1]
        dataAbsentReason : CodeableConcept [0..1]
        interpretation : CodeableConcept [0..*]
    }

    object Findings {
        code : CodeableConcept
        valueQuantity : Quantity
    }

}



Observation::X1 "1" -right-> "1" Findings::code
DiagnosticReport::result "1" <-* "N" Observation
Observation::value -> Component
Observation::bodySite --> BodySite

'map CapitalCity {
'DiagnosticReport *-> DiagnosticReport
'' UK *-> London
'' USA *--> Washington
'' Germany *---> Berlin
'}

'NewYork --> CapitalCity::USA
@enduml
