@startuml PERT
'https://plantuml.com/object-diagram

scale 600 height
hide @unlinked


left to right direction

object DiagnosticReport {
    identifier : Identifier
    basedOn : Reference
    status : code [1..1]
    category : CodeableConcept
  + <b><color brown>code : CodeableConcept [1..1]</color></b> <color #eee>X1</color>
    subject : Reference [0..1]
    encounter : Reference [0..1]
    effective[x] : DataType [0..1]
    issued : instant [0..1]
    performer : Reference
    resultsInterpreter : Reference
    specimen : Reference
  + <b><color brown>result : Reference</color></b>
    note : Annotation
    imagingStudy : Reference
    composition : Reference [0..1]
    conclusion : string [0..1]
    conclusionCode : CodeableConcept
    presentedForm : Attachment
    Media
    comment : string [0..1]
    link : Reference [1..1]
}
note bottom
  for highly structured report,
    otherwise, use composition
end note

DiagnosticReport::basedOn -- Procedure
DiagnosticReport::result o--- "1..*" Observation

object ImagingStudy{

}


object Observation{
    identifier : Identifier
  +  <b><color brown>code : CodeableConcept [1..1]</color></b> <color #eee>X1</color>
  +  <b><color brown>bodySite : CodeableConcept [0..1]</color></b>
  +  <b><color brown>value[x] : DataType [0..1]</color></b>
    instantiates[x] : DataType [0..1]
    basedOn : Reference
    partOf : Reference
    status : code [1..1]
    category : CodeableConcept
    subject : Reference [0..1]
    focus : Reference
    encounter : Reference [0..1]
    effective[x] : DataType [0..1]
    issued : instant [0..1]
    performer : Reference
    dataAbsentReason : CodeableConcept [0..1]
    interpretation : CodeableConcept
    note : Annotation
    method : CodeableConcept [0..1]
    specimen : Reference [0..1]
    device : Reference [0..1]
    hasMember : Reference
    derivedFrom : Reference
    ReferenceRange
    low : Quantity(SimpleQuantity) [0..1]
    high : Quantity(SimpleQuantity) [0..1]
    type : CodeableConcept [0..1]
    appliesTo : CodeableConcept
    age : Range [0..1]
    text : string [0..1]
}


object BodySite {

}

note bottom
  The BodyStructure resource is
  an immature resource with an
  FMM level of 1
end note

object Component1 {
    code : CodeableConcept [1..1]
    value[x] : DataType [0..1]
    dataAbsentReason : CodeableConcept [0..1]
    interpretation : CodeableConcept [0..*]
}

object Component2 {
    code : CodeableConcept [1..1]
    value[x] : DataType [0..1]
    dataAbsentReason : CodeableConcept [0..1]
    interpretation : CodeableConcept [0..*]
}

object Component3 {
    code : CodeableConcept [1..1]
    value[x] : DataType [0..1]
    dataAbsentReason : CodeableConcept [0..1]
    interpretation : CodeableConcept [0..*]
}

object ValueSet {
    code : $sct#251015000 "Coronary artery finding"
}

<> d1

object ValueSet2{
    bodySite: $sct#67734004 "Upper Trunk Structure"
}

Observation::X1 "1" ---> "1" ValueSet::code
Observation::bodySite ---> ValueSet2
Observation::value ---> d1
d1 ---> Component1
d1 ---> Component2
d1 ---> Component3

@enduml
