@startuml PERT
'https://plantuml.com/object-diagram

scale 600 height
hide @unlinked

left to right direction

object Bundle {
'    identifier : Identifier [0..1]
'    type : code [1..1] « BundleType! »
'    timestamp : instant [0..1]
'    total : unsignedInt [0..1]
'    signature : Signature [0..1]
    + entry : BackboneElement [0..*]
}

object Entry {
    fullUrl : uri [0..1]
    + resource : Resource [0..1]
}

Bundle *--"0..*" Entry : entry

object Patient {
}

object Composition {
'    url : uri [0..1]
'    identifier : Identifier [0..1]
'    version : string [0..1]
    +status : code [1..1] « CompositionStatus! »
    +type : CodeableConcept [1..1] « FHIRDocumentTypeCodes? »
'    category : CodeableConcept [0..*] « ReferencedItemCategoryValueSet?? »
'    subject : Reference [0..1] « Any »
'    encounter : Reference [0..1] « Encounter »
    +date : dateTime [1..1]
'    useContext : UsageContext [0..*]
'    author : Reference [1..*] « Practitioner|PractitionerRole|Device|
'    Patient|RelatedPerson|Organization »
'    name : string [0..1]
    +title : string [1..1]
'    note : Annotation [0..*]
'    confidentiality : code [0..1] « Confidentiality! »
'    custodian : Reference [0..1] « Organization »
'    relatesTo : RelatedArtifact [0..*]
}

object Section {
    title : string [0..1]
    code : CodeableConcept [0..1] « DocumentSectionCodes?? »
'    author : Reference [0..*] « Practitioner|PractitionerRole|Device|
'    Patient|RelatedPerson|Organization »
'    focus : Reference [0..1] « Any »
'    text : Narrative [0..1]
'    mode : code [0..1] « ListMode! »
'    orderedBy : CodeableConcept [0..1] « ListOrderCodes? »
    entry : Reference [0..*] « Any »
'    emptyReason : CodeableConcept [0..1] « ListEmptyReasons? »
}

Composition *--"0..*" Section : section
Section *--"0..*" Section : section

Section *--"0..*" Observation : entry???

object Organization {
}

object ImagingStudy {
    identifier : Identifier [0..*]
    status : code [1..1] « ImagingStudyStatus! »
'    modality : CodeableConcept [0..*] « ImagingModality+ »
    subject : Reference [1..1] « Patient|Device|Group »
'    encounter : Reference [0..1] « Encounter »
    started : dateTime [0..1]
'    basedOn : Reference [0..*] « CarePlan|ServiceRequest|Appointment|
'    AppointmentResponse|Task »
'    referrer : Reference [0..1] « Practitioner|PractitionerRole »
'    interpreter : Reference [0..*] « Practitioner|PractitionerRole »
'    endpoint : Reference [0..*] « Endpoint »
    numberOfSeries : unsignedInt [0..1]
    numberOfInstances : unsignedInt [0..1]
'    procedure : DataType [0..*] « Procedure; ImagingProcedureCode? »
'    location : Reference [0..1] « Location »
'    reason : DataType [0..*] « Condition|Observation|DiagnosticReport|
'    DocumentReference; ProcedureReasonCodes?? »
'    note : Annotation [0..*]
'    description : string [0..1]
    +series : BackboneElement [0..*]
}

object Binary{
    contentType
    data
}

object Series{
    uid : id [1..1]
    number : unsignedInt [0..1]
    modality : CodeableConcept [1..1] « ImagingModality+ »
    description : string [0..1]
    numberOfInstances : unsignedInt [0..1]
'    endpoint : Reference [0..*] « Endpoint »
    bodySite : DataType [0..1] « BodyStructure; SNOMEDCTBodyStructures?? »
'    laterality : CodeableConcept [0..1] « Laterality?? »
'    specimen : Reference [0..*] « Specimen »
'    started : dateTime [0..1]
    +instance : BackboneElement [0..*]
}

Entry *--"0..*" Patient : resource
Entry *--"0..*" Composition : resource
Entry *--"0..*" Organization : resource
Entry *--"0..*" ImagingStudy : resource
Entry *--"0..*" DiagnosticReport : resource
Entry *--"0..*" Binary : resource

ImagingStudy *--"0..*" Series : series
Series *--"0..1" BodySite : bodySite

object Instance {
    uid : id [1..1]
    number : unsignedInt [1..1]
    sopClass : code [1..1] « SOPClass! »
}
Series *--"0..*" Instance : instance

object DiagnosticReport {
'    identifier : Identifier
'    basedOn : Reference
'    status : code [1..1]
'    category : CodeableConcept
  + <b><color brown>code : CodeableConcept [1..1]</color></b> <color #eee>X1</color>
'    subject : Reference [0..1]
'    encounter : Reference [0..1]
'    effective[x] : DataType [0..1]
'    issued : instant [0..1]
'    performer : Reference
'    resultsInterpreter : Reference
'    specimen : Reference
  + <b><color brown>result : Reference</color></b>
'    note : Annotation
    imagingStudy : Reference
'    composition : Reference [0..1]
'    conclusion : string [0..1]
'    conclusionCode : CodeableConcept
'    presentedForm : Attachment
'    Media
'    comment : string [0..1]
'    link : Reference [1..1]
}
note bottom
  for highly structured report,
    otherwise, use composition
end note

'DiagnosticReport::basedOn -- Procedure
DiagnosticReport::result o--- "[1..*]" Observation : result


object Observation{
'    identifier : Identifier
  +  <b><color brown>code : CodeableConcept [1..1]</color></b> <color #eee>X1</color>
  +  <b><color brown>bodySite : CodeableConcept [0..1]</color></b>
  +  <b><color brown>value[x] : DataType [0..1]</color></b>
'    instantiates[x] : DataType [0..1]
    basedOn : Reference
    partOf : Reference
    status : code [1..1]
    category : CodeableConcept
'    subject : Reference [0..1]
'    focus : Reference
'    encounter : Reference [0..1]
'    effective[x] : DataType [0..1]
'    issued : instant [0..1]
'    performer : Reference
    dataAbsentReason : CodeableConcept [0..1]
'    interpretation : CodeableConcept
'    note : Annotation
'    method : CodeableConcept [0..1]
'    specimen : Reference [0..1]
    device : Reference [0..1]
    hasMember : Reference
    derivedFrom : Reference
'    ReferenceRange
'    low : Quantity(SimpleQuantity) [0..1]
'    high : Quantity(SimpleQuantity) [0..1]
'    type : CodeableConcept [0..1]
'    appliesTo : CodeableConcept
'    age : Range [0..1]
'    text : string [0..1]
     component : BackboneElement [0..*]
}

object BodySite {

}

note bottom
  The BodyStructure resource is
  an immature resource with an
  FMM level of 1
end note

object Component1 {
    code = $sct#386139002	"Stenotic"
    valueCodeableConcept = $phy#1000	"轻度狭窄"
}

object Component2 {
  * code = $sct#386138005	"Stented"
  * valueCodeableConcept = $phy#1001	"无"
}

object Component3 {
  * code = $sct#237897009	"Calcified" //"钙化斑块"
  * valueCodeableConcept = $phy#1010	"有"
}

object Component4 {
  * code = $phy#1020	"混合斑块"
  * valueCodeableConcept = $phy#1010	"有"
}

object ValueSet {
    code : $sct#251015000 "Coronary artery finding"
}

<> d1

object ValueSet2{
    bodySite: $sct#67734004 "Upper Trunk Structure"
}

Observation::X1 "1" ---> "1" ValueSet::code
Observation::bodySite ---> ValueSet2
Observation::component ---> d1 : component
d1 ---> Component1
d1 ---> Component2
d1 ---> Component3
d1 ---> Component4

object ImagingSelection {
    identifier : Identifier [0..*]
    subject : Reference [0..1] « Patient|Group|Device|Location|
'    Organization|Procedure|Practitioner|Medication|Substance|
'    Specimen »
'    issued : instant [0..1]
'    basedOn : Reference [0..*] « CarePlan|ServiceRequest|Appointment|
'    AppointmentResponse|Task »
'    category : CodeableConcept [0..*] « ImagingSelectionCode?? »
    code : CodeableConcept [1..1] « ImagingSelectionCode?? »
    studyUid : oid [0..1]
    derivedFrom : Reference [0..*] « ImagingStudy »
'    endpoint : Reference [0..*] « Endpoint »
    seriesUid : oid [0..1]
    frameOfReferenceUid : oid [0..1]
'    bodySite : DataType [0..1] « BodyStructure; SNOMEDCTBodyStructures?? »
    imageRegion : BackboneElement [0..1]
}

object ImageRegion{
    +regionType : code [1..1] « ImagingSelectionGraphicType! »
    +coordinateType : code [1..1] « ImagingSelectionCoordinateType! »
    +coordinate : decimal [1..*]
}

ImagingSelection *--"[0..1]" ImageRegion : imageRegion
ImagingSelection *--"[0..*]" ImagingStudy : derivedFrom

@enduml
