@startuml
'https://plantuml.com/state-diagram

scale 350 width

state "Simplifier.net" as S
    S: //view the resource, validate the data//

state "FSH" as F
    F: //compile and generate resource//

state "Forge" as G
    G: //edit graphically//

F --> S : shushi\nzip\nupload
S -[#888,dashed]-> F : GoFSH \n(in theory)

S --> G : edit\nupload\ndownload



@enduml