@startuml
'https://plantuml.com/sequence-diagram

skinparam maxMessageSize 250
scale 800 width
autonumber

actor "Patient" as patient
actor "Doctor" as doctor
actor "Nurse" as nurse
actor "Pharmacist" as pharmacist
actor "Radiologist" as radiologist
actor "X-Ray Technician" as xraytechnician
actor "Cardiologist" as cardiologist
actor "Surgeon" as surgeon
actor "Anesthesiologist" as anesthesiologist
actor "Pathologist" as pathologist
actor "Psychiatrist" as psychiatrist
actor "Third Party" as thirdparty
actor "AI algorithm" as ai

participant RIS as RIS
participant PACS as PACS
participant EMR as EMR
participant ISAI as ISAI

participant "RIS" as R
participant "Modality" as M
participant "PACS" as P
participant "ISAI" as I
participant "AI algorithm" as S


hide @unlinked

'group CTA
'patient -> doctor: I need a doctor
'cardiologist -> pathologist:
'end

 -> R: patient\nregistration\ninformation

'R -> I++: patient registration（VDO)
'return worklist

R -> M: send worklist
M -> M: image acquisition
M -> P: send DICOM images
P++
P -[dotted]-> R: notify image acquisition completed


group ISAI
    note over I
    * ISAI will:
    - generate a list of AI requests
    - send AI requests to AI servers
    - receive AI responses
    end note

    P -> I++: notify image ready
    P--

    I -> I: AI algorithm orchestration
    note over I
    * Identify AI request based on:
    - orders from physician (e.g. CT, MRI, PET)
    - pre-set rules, such as:
      - patient age, risk factors, etc.
      - body parts / modality
    end note

    I -> P++: DICOM Q/R images
    note over I
    * potentially load more patient data from EMR
    end note
    return DICOM images

    I -> S++: starty AI algorithm
    I -[dotted]-> R: AI algorithm running status
    S -> S: AI application execution\n(algorithm provided by AI vendors with docker image）
    return AI algorithm results
    I -> R++: send AI execution result
    note over R
    Physician receive AI execution result
    review the AI result, and decide whether
    to accept or reject the result.
    end note
    ...
    return The confirmation from the physician
    I -> S: send the confirmed results(key image/json)
    I -> P: send the AI-processed images
end


@enduml