@startuml
'https://plantuml.com/sequence-diagram

skinparam maxMessageSize 150
scale 500 width
autonumber

actor "Patient" as patient
actor "Doctor" as doctor
actor "Nurse" as nurse
actor "Pharmacist" as pharmacist
actor "Radiologist" as radiologist
actor "X-Ray Technician" as xraytechnician
actor "Cardiologist" as cardiologist
actor "Surgeon" as surgeon
actor "Anesthesiologist" as anesthesiologist
actor "Pathologist" as pathologist
actor "Psychiatrist" as psychiatrist
actor "Third Party" as thirdparty
actor "AI algorithm" as ai

participant RIS as RIS
participant PACS as PACS
participant EMR as EMR
participant ISAI as ISAI

participant "RIS" as R
participant "Modality" as M
participant "PACS" as P
participant "ISAI" as I
participant "SMIT SR" as S


hide @unlinked

'group CTA
'patient -> doctor: I need a doctor
'cardiologist -> pathologist:
'end

 -> R: patient\nregistration\ninformation

'R -> I++: patient registration（VDO)
'return worklist

R -> M: send worklist
M -> M: image acquisition
M -> P: send DICOM images
P -> R: notify image acquisition completed
P -> I: notify image acquisition completed(VDO)

I -> I: Filtering for notification based on supported modality type and body part

group
    P <- I: DICOM Q/R images
    P -> I:
    I -> I: AI application execution (algorithm provided by AI vendors with docker image）
    I -> R: send AI execution running status
    R -> I: confirm results by invoking the ISAI result audit dashboard
    I -> S: send the confirmed results(key image/json)
    I -> P: send the AI-processed images
end


@enduml