@startuml
skinparam maxMessageSize 150
scale 500 width

participant "RIS" as R
participant "Modality" as M
participant "ISAI" as I
participant "3rd party\nalgorithms" as S

 -> R : Imaging Order
R -> M++: Worklist
loop
M -> M: Scan
M -> I++: Request for AI algorithm
I -> M++: load image
return
group Algorithm
I -> S ++: Start AI algorithm
S -> S: calculation
return AI result / Findings
end
return Algorithm result
note over M
User interactively
manipulate the
image.
The final result is
saved to PACS.
end note
end
return AI Result / Structural report
 <- R: Structural Report

@enduml
